### ISSUE TITLE
props name for handling event callback

### ISSUE THREAD

**Issue by AllenFang** [joanna8030/rakuten-react-training#3]
You should use `onXXX` as the props name for presenting the event triggering, for example,

``` js
render() {
    return (
        <Component 
           onClick={ this.handleXXXClick }
           onHover={ this.handleXXXHover }
    );
}
```

check [index.js](https://github.com/joanna8030/rakuten-react-training/blob/dev/src/index.jsx#L64-L66), this three line can be changed like following

``` js
onDropRow={this.handleDrop}
onEditRow={this.handleEdit}
onEditBtnClick={this.handleModal}
```

I believe it's more intuitive when someone review your code.

**Comment by rebecca-chen** [comment]
Thanks a lot!

**Comment by AllenFang** [comment]
https://github.com/joanna8030/rakuten-react-training/commit/f69350221aba93d077c6c5a532c003da8ed1910c#commitcomment-19379376

Follow this pattern, you still did the wrong fixed

``` js
onDropRow={this.handleDropRow}
onEditRow={this.handleEditRow}
onEditBtnClick={this.handleModalOpen}
```

**Comment by rebecca-chen** [comment]
got it!
Is that correct?

**Comment by AllenFang** [comment]
@joanna8030, perfect. Dont forget that there's a `redux` homework you need to do. Work hard and keep going.
